/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.vng.zing.resource.thrift;

public enum UserType implements org.apache.thrift.TEnum {
    REGULAR(0),
    PREMIUM(1),
    ADMIN(2);

    private final int value;

    private UserType(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     *
     * @return null if the value is not found.
     */
    public static UserType findByValue(int value) {
        switch (value) {
            case 0:
                return REGULAR;
            case 1:
                return PREMIUM;
            case 2:
                return ADMIN;
            default:
                return null;
        }
    }
}
